version: "3"
services:
  postgres:
    image: 'postgres:latest'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "4200:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/frontend/node_modules
      - ./frontend:/app/frontend
    restart: always